### ISSUE TITLE
api/replays/?owned seems not to work

### ISSUE THREAD

**Issue by IDeserveToBeWrited** [rocket-league-replays/rocket-league-replays#105]
Either I'm doing something wrong (which has a high probability) or ?owned parameter doesn't work.
In browser and with wget (with imported cookies from logged in browser) I'm getting regular api/replays response.

**Comment by danielsamuels** [comment]
Are you passing an API key in as authorisation?

**Comment by IDeserveToBeWrited** [comment]
No, how to do it?
