### ISSUE TITLE
Add a tournament system

### ISSUE THREAD

**Issue by danielsamuels** [rocket-league-replays/rocket-league-replays#16]
Similar to what is on rocket-league.com

Additional features:
- Replay file uploads per game for verification purposes
- Create replay packs from tournaments?

**Comment by chase4646** [comment]
Hi Daniel,

Regarding your first point on replay file uploads as game verification - I've been exploring this idea and think it has potential. One of the issues I am seeing on private servers is a player's ability to join/leave/change teams at any time in the match.

How difficult would it be to parse out a log of player join/leave events? Thinking of an output looking something like this:

```json
"player_event_set":[  
   {  
      "time":"0:28",
      "player_id":4284245,
      "event":"joined team: orange"
   },
   {  
      "time":"0:28",
      "player_id":4284245,
      "event":"disconnected"
   },
   {  
      "time":"0:42",
      "player_id":4284245,
      "event":"joined team: blue"
   },
   {
      "time":"2:12",
      "player_id":4284245,
      "event":"became spectator"
   }
],

Is this data available in the replay, and is it feasible to extract?

**Comment by danielsamuels** [comment]
Definitely possible, all of the data is there.

**Comment by chase4646** [comment]
Perfect, thanks very much - will give it a go.

**Comment by chase4646** [comment]
I guess this one can be dropped off the roadmap with tournaments now built into the game client?

**Comment by danielsamuels** [comment]
I guess so!
