### ISSUE TITLE
Write a replay parser in Go

### ISSUE THREAD

**Issue by danielsamuels** [rocket-league-replays/rocket-league-replays#24]
This should be faster than a Python 3 implementation if written correctly.

**Comment by tfausak** [comment]
Any particular reason for choosing Go? It might be the only language that doesn't have a replay parser yet :)

As you know, there's [one in C#](https://github.com/jjbott/RocketLeagueReplayParser), [another in Elixir](https://github.com/rustyfausak/gizmo-elixir), and [mine in Haskell](https://github.com/tfausak/octane). I don't know about C# and Elixir, but mine can be statically compiled. I could also make it output the same JSON as the current Python parser.
