### ISSUE TITLE
Allow the replay list api call to pass some replay metadata

### ISSUE THREAD

**Issue by calvinbaart** [rocket-league-replays/rocket-league-replays#25]
Hi there!

I'm currently creating a replay analyzer in javascript:
http://puu.sh/nHVZk/0eaa440a96.png
(I know, I suck at UI design)

And I would like to have a "browse rocketleaguereplays.com" feature so that the analyzer is able to
download replays from your site to analyze. However, showing alot of URL's doesn't really make sense (which is what /api/replays/ returns) and iterating and processing all of the URL's is probably going to give your site alot of unnecessary traffic. So it would be nice if we could get some basic metadata when requesting the replay list. Something like:
- Replay ID
- Team1 Score
- Team2 Score
- Map
- PlayerList
Would help alot.

The alternative would be one of:
1) Actually iterate over all the urls to download the metadata per url
2) Just show the plain id's and let the user figure out which replay they want (not really a fan of this one)
3) Don't show a list but show a download by id option where you enter an id from rocketleaguereplays.com (Would be ok I guess, but would be nicer if there was a list)

**Comment by danielsamuels** [comment]
Sorry, for some reason I didn't receive a notification for this issue. The API (and the replays in general) are something I'm going to be looking at soon. I'll take this feedback into account when I'm making those updates.

**Comment by danielsamuels** [comment]
Closed via cd73eda.
