### ISSUE TITLE
Wrong ratings

### ISSUE THREAD

**Issue by inyono** [rocket-league-replays/rocket-league-replays#33]
Currently, Rocket League Replays shows wrong rankings for me. I.e. https://www.rocketleaguereplays.com/steam/76561198019960809/ (incorrect) vs. https://rocketleaguestats.com/profile/steam/76561198019960809 (correct).

**Comment by danielsamuels** [comment]
Thanks for the report, I'll look into it.

**Comment by inyono** [comment]
it seems fine now after another play session (with uploads)

**Comment by inyono** [comment]
Currently, it's broken again. E.g., Rocket League Replays shows me a rating for "Standard" although I haven't played that yet in this season.

**Comment by danielsamuels** [comment]
I'm working on changing the way rankings are pulled in, so this should be fixed in the next couple of days.

**Comment by danielsamuels** [comment]
Should now be fixed!
