### ISSUE TITLE
Getting "Unknown error" when trying to upload a replay from Linux

### ISSUE THREAD

**Issue by abcde13** [rocket-league-replays/rocket-league-replays#37]
I was using the app on Windows, but since there  is no linux build, I was just uploading files.

However, no matter which replay I upload, I get an "Unknown error" after it hits 100%.

![rlreplayerror](https://cloud.githubusercontent.com/assets/894122/20206520/d4f54296-a795-11e6-9854-dfb745a0cfff.png)

The first one is a reupload of a RLCS S2 Euro League Play Week 4 match. I wanted to see if it was all files uploading from linux, or just my files. It seems to be just my file. 

[This Dropbox link](https://www.dropbox.com/s/9v3185oi2hu5du2/3832A01811E6A7D4F5A7D18F448F3E30.replay?dl=0) has the replay I want to upload in particular.

Are linux replays in some different format that uploading can't parse properly?

**Comment by tfausak** [comment]
@danielsamuels this is my fault.

``` fish
Downloads> ./octane --version
0.16.3
Downloads> ./octane 3832A01811E6A7D4F5A7D18F448F3E30.replay /dev/null
octane: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary.hs:218:21 in binary-0.8.3.0:Data.Binary
```

My [new tool](https://github.com/tfausak/rattletrap) handles this replay correctly. That means I need to hurry up with https://github.com/tfausak/octane/pull/68.

**Comment by danielsamuels** [comment]
@tfausak No worries, I'll wait on that issue.

**Comment by danielsamuels** [comment]
This should be fixed in the latest version.
