### ISSUE TITLE
Boost Consumption Incorrect for Some Players

### ISSUE THREAD

**Issue by abcde13** [rocket-league-replays/rocket-league-replays#92]
Now, it's not that I know exactly how much boost a player used just by looking at the Large and Small Pickups on the board. However, take http://www.rocketleaguereplays.com/replays/375013d3-4065-fbb0-a475-bbbea0e343f1/boost-analysis/ for example.

Denial CorruptedG picked up 12 Large and 20 Small Pickups in this game, and consumed 1754 boost. With the boost he picked up, he could have only consumed 12\*100 + 20\*12 = 1440 boost maximum, so where is the 1754 boost coming from? 

I've attached a csv of all the players and games (at least in the RLCS S3 League Play packs uploaded)
as data for confirming the problem and as test cases to fix. The Game # is denoted in such a way that "NA 1-1" means "RLCS League Play NA Week 1, Game 1" where Game 1 is the first match in the list when you open that week.

**Comment by danielsamuels** [comment]
There's a column which isn't shown any more, but it's called "Unknown boost pickups" and it basically encapsulates any pickups which couldn't be properly categorised. There's some weird edge-cases where it can't determine whether a small or large boost was collected and therefore it doesn't categorise the pickups as either.  The total amount collected will be correct, and the small / large pickups mostly correct.

**Comment by jscrally** [comment]
Oh, interesting. Alright, as long as they are fully correct in their own way! This issue can be closed.
